/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.uw.complexkotlin

import kotlin.test.*

class LibraryTest {
    @Test fun fizzbuzzToTwo() {
        assertEquals("", fizzbuzz(1..2))
    }

    @Test fun fizzbuzzToFifteen() {
        assertEquals("FIZZBUZZFIZZDOHFIZZBUZZFIZZDOHFIZZBUZZ", fizzbuzz(1..15))
    }
    @Test fun fizzbuzzToTwelve() {
        assertEquals("FIZZBUZZFIZZDOHFIZZBUZZFIZZ", fizzbuzz(1..12))
    }
    @Test fun fizzbuzzToFifty() {
        assertEquals("FIZZBUZZFIZZDOHFIZZBUZZFIZZDOHFIZZBUZZFIZZBUZZFIZZFIZZBUZZFIZZDOHFIZZBUZZFIZZBUZZFIZZFIZZBUZZFIZZFIZZBUZZFIZZDOHBUZZ", fizzbuzz(1..50))
    }
    @Test fun fizzbuzzToHundred() {
        assertEquals("FIZZBUZZFIZZDOHFIZZBUZZFIZZDOHFIZZBUZZFIZZBUZZFIZZFIZZBUZZFIZZDOHFIZZBUZZFIZZBUZZFIZZFIZZBUZZFIZZFIZZBUZZFIZZDOHBUZZFIZZFIZZBUZZDOHFIZZFIZZBUZZFIZZBUZZFIZZFIZZBUZZFIZZFIZZBUZZDOHFIZZBUZZFIZZFIZZBUZZFIZZFIZZBUZZDOHFIZZBUZZFIZZDOHFIZZBUZZ", fizzbuzz(1..100))
    }
    @Test fun fizzbuzzGenOddToTwo() {
        assertEquals("", fizzbuzzGen(mapOf(3 to "FIZZ", 5 to "BUZZ"))(1..2))
    }
    @Test fun fizzbuzzGenEvenToTwo() {
        assertEquals("FIZZ", fizzbuzzGen(mapOf(2 to "FIZZ", 4 to "BUZZ"))(1..2))
    }
    @Test fun fizzbuzzGenWeird() {
        assertEquals("Hello World!", fizzbuzzGen(mapOf(3 to "Hello ", 5 to "World!"))(1..5))
    }

    @Test fun r1Test() {
        assertEquals(">>> FOO: {BAR}", r1())
    }
    @Test fun r2Test() {
        assertEquals(">>> FOO: {WOOGAWOOGAWOOGA}", r2())
    }

    @Test fun philosopherTests() {
        var seneca = Philosopher.THINKING
        assertEquals("Deep thoughts....", seneca.toString())

        // Shift to talking
        seneca = seneca.signal()
        assertEquals("Allow me to suggest an idea...", seneca.toString())

        // Shift to thinking
        seneca = seneca.signal()
        assertEquals("Deep thoughts....", seneca.toString())

        // Shift back to talking
        seneca = seneca.signal()
        assertEquals("Allow me to suggest an idea...", seneca.toString())
    }

    @Test fun commandTests() {
        assertEquals("", Command("")(""))
        assertEquals("> Hello!", Command("> ")("Hello!"))
    }
}
